source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = '#{repo_name}/#{repo_name}' unless repo_name.include?('/')
  'https://github.com/#{repo_name}.git'
end

gem 'rails'
gem 'pg'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
gem 'puma'
gem 'slim-rails'
gem 'uglifier'
gem 'turbolinks'
gem 'jbuilder'
gem 'multi_json'
gem 'serviceworker-rails'
gem 'rake'
gem 'dotenv-rails'
gem 'graphql'
gem 'multiverse'
gem 'composite_primary_keys', '=11.1.0'
gem 'lograge'
gem 'logstash-event'

group :development, :test do
  gem 'listen'
  gem 'pry-rails'
  gem 'guard'
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'guard-rubocop'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'awesome_print'
  gem 'factory_bot_rails'
  gem 'graphiql-rails'
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'simplecov', require: false
  gem 'simplecov-rcov', require: false
  gem 'database_cleaner'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
